#pragma once
#include <windows.h>
#include <exception>
#include <vector>
#include <iostream>
#include "xorstr.hpp"
#include "ra.h"



namespace utils {
	extern void SetWindowVisible(bool visible, HWND hWnd);
	extern void SetWindowPosition(HWND top, HWND bottom);
	extern void SetWindowClickable(bool clickable, HWND hWnd);
	extern bool key_down(int virtual_keycode);
	extern void query_sleep(int ms);
	extern float random_float(float a, float b);
	extern void relative_mouse_move(double delay, double control_time, float x, float y);
	void echo_error(const std::exception& e, int code);
	int rust_key_to_virtual_key(const char* rust_key);
    void mouse_press();
    void save_cfg();
    void load_cfg();
    bool check();
    bool correct(std::string name);

    const std::vector <std::string> RustKeys{
    XorStr("Unknown"),
    XorStr("mouse0"),
    XorStr("mouse1"),
    XorStr("VK_CANCEL"),
    XorStr("mouse2"),
    XorStr("mouse3"),
    XorStr("mouse4"),
    XorStr("Unknown"),
    XorStr("back"),
    XorStr("tab"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("VK_CLEAR"),
    XorStr("return"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("leftshift"),
    XorStr("leftcontrol"),
    XorStr("menu"),
    XorStr("VK_PAUSE"),
    XorStr("VK_CAPITAL"),
    XorStr("VK_KANA"),
    XorStr("Unknown"),
    XorStr("VK_JUNJA"),
    XorStr("VK_FINAL"),
    XorStr("VK_KANJI"),
    XorStr("Unknown"),
    XorStr("escape"),
    XorStr("VK_CONVERT"),
    XorStr("VK_NONCONVERT"),
    XorStr("VK_ACCEPT"),
    XorStr("VK_MODECHANGE"),
    XorStr("space"),
    XorStr("VK_PRIOR"),
    XorStr("VK_NEXT"),
    XorStr("end"),
    XorStr("home"),
    XorStr("left"),
    XorStr("up"),
    XorStr("right"),
    XorStr("down"),
    XorStr("VK_SELECT"),
    XorStr("VK_PRINT"),
    XorStr("VK_EXECUTE"),
    XorStr("VK_SNAPSHOT"),
    XorStr("VK_INSERT"),
    XorStr("VK_DELETE"),
    XorStr("VK_HELP"),
    XorStr("0"),
    XorStr("1"),
    XorStr("2"),
    XorStr("3"),
    XorStr("4"),
    XorStr("5"),
    XorStr("6"),
    XorStr("7"),
    XorStr("8"),
    XorStr("9"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("a"),
    XorStr("b"),
    XorStr("c"),
    XorStr("d"),
    XorStr("e"),
    XorStr("f"),
    XorStr("g"),
    XorStr("h"),
    XorStr("i"),
    XorStr("j"),
    XorStr("k"),
    XorStr("l"),
    XorStr("m"),
    XorStr("n"),
    XorStr("o"),
    XorStr("p"),
    XorStr("q"),
    XorStr("r"),
    XorStr("s"),
    XorStr("t"),
    XorStr("u"),
    XorStr("v"),
    XorStr("w"),
    XorStr("x"),
    XorStr("y"),
    XorStr("z"),
    XorStr("VK_LWIN"),
    XorStr("VK_RWIN"),
    XorStr("VK_APPS"),
    XorStr("Unknown"),
    XorStr("VK_SLEEP"),
    XorStr("keypad0"),
    XorStr("keypad1"),
    XorStr("keypad2"),
    XorStr("keypad3"),
    XorStr("keypad4"),
    XorStr("keypad5"),
    XorStr("keypad6"),
    XorStr("keypad7"),
    XorStr("keypad8"),
    XorStr("keypad9"),
    XorStr("VK_MULTIPLY"),
    XorStr("VK_ADD"),
    XorStr("VK_SEPARATOR"),
    XorStr("VK_SUBTRACT"),
    XorStr("VK_DECIMAL"),
    XorStr("VK_DIVIDE"),
    XorStr("f1"),
    XorStr("f2"),
    XorStr("f3"),
    XorStr("f4"),
    XorStr("f5"),
    XorStr("f6"),
    XorStr("f7"),
    XorStr("f8"),
    XorStr("f9"),
    XorStr("f10"),
    XorStr("f11"),
    XorStr("f12"),
    XorStr("f13"),
    XorStr("f14"),
    XorStr("f15"),
    XorStr("f16"),
    XorStr("f17"),
    XorStr("f18"),
    XorStr("f19"),
    XorStr("f20"),
    XorStr("f21"),
    XorStr("f22"),
    XorStr("f23"),
    XorStr("f24"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("VK_NUMLOCK"),
    XorStr("VK_SCROLL"),
    XorStr("VK_OEM_NEC_EQUAL"),
    XorStr("VK_OEM_FJ_MASSHOU"),
    XorStr("VK_OEM_FJ_TOUROKU"),
    XorStr("VK_OEM_FJ_LOYA"),
    XorStr("VK_OEM_FJ_ROYA"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("Unknown"),
    XorStr("leftshift"),
    XorStr("rightshift"),
    XorStr("leftcontrol"),
    XorStr("rightcontrol"),
    XorStr("VK_LMENU"),
    XorStr("VK_RMENU")
    };
}